<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MSCIP15" failures="4" tests="4" name="Sign Up Tests" time="96.062" errors="0" timestamp="2025-07-12T09:12:08 GMT-07:00">
  <testcase classname="tests.SignUpTests" name="testSignUpScenarios" time="21.403">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	User should be registered successfully expected [success] but found [Unknown error]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
User should be registered successfully expected [success] but found [Unknown error]
at tests.SignUpTests.testSignUpScenarios(SignUpTests.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testSignUpScenarios -->
  <testcase classname="tests.SignUpTests" name="testSignUpScenarios" time="21.483">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected error message to contain: Email address is already in use, but was: Unknown error expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected error message to contain: Email address is already in use, but was: Unknown error expected [true] but found [false]
at tests.SignUpTests.testSignUpScenarios(SignUpTests.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testSignUpScenarios -->
  <testcase classname="tests.SignUpTests" name="testSignUpScenarios" time="21.527">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected error message to contain: User validation failed, but was: Unknown error expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected error message to contain: User validation failed, but was: Unknown error expected [true] but found [false]
at tests.SignUpTests.testSignUpScenarios(SignUpTests.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testSignUpScenarios -->
  <testcase classname="tests.SignUpTests" name="testSignUpScenarios" time="21.482">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Expected error message to contain: User validation failed, but was: Unknown error expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Expected error message to contain: User validation failed, but was: Unknown error expected [true] but found [false]
at tests.SignUpTests.testSignUpScenarios(SignUpTests.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testSignUpScenarios -->
</testsuite> <!-- Sign Up Tests -->
